### ISSUE TITLE
strapi crashen on server restart after settting the config

### ISSUE THREAD

**Issue by Clex1o1** [lachoseparis/lachose-strapi-plugins#2]
Hi,

I installed the plugin on strapi v4.5.2 on node 18.8.0 and npm 8.18.0. 
After configuring in the settings the automatic server restart crashed with:
```
Error: write EPIPE
    at target._send (node:internal/child_process:865:20)
    at target.send (node:internal/child_process:738:19)
    at Worker.send (node:internal/cluster/worker:48:10)
    at EventEmitter.<anonymous> (.../node_modules/@strapi/strapi/lib/commands/develop.js:92:16)
SentryError: HTTP Error (429)
    at new SentryError (/Users/alexanderclassen/Projects/integer/backend/node_modules/@sentry/utils/dist/error.js:9:28)
    at ClientRequest.<anonymous> (/Users/alexanderclassen/Projects/integer/backend/node_modules/@sentry/node/dist/transports/base/index.js:214:44)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
```

After manually restating the develop server the config option is not set.

Not sure, what sentry does in this setup 😅 i haven't configured it.

**Comment by Clex1o1** [comment]
Ah it seems it is a typescript error. I'm using strapi with typescript. This plugin creates a `.js` file which causes in an error. If I rename it to `.ts` the configuration is in strapi, but i cannot reconfigure it, because the plugin creates another `.js` file. 
Any plans for typescript support?

**Comment by nitinTJ** [comment]
Facing the same issue

**Comment by sparrow-chik-chrk** [comment]
Hi, is there a solution for this? It seems like the support for the plugin has been discontinued, am I right?
